import { Observable, of } from 'rxjs';
import { StorageInterface } from '../angular/port/storage.interface';
import { Scan } from '../core/src/domain/scan.type';

export class InMemoryStorageService implements StorageInterface {
  updateScan(scan: Scan): void {
    console.log('scan is updated');
  }
  getScans(): Observable<Scan[]> {
    return of([
      {
        chapter: '9999',
        title: 'Local',
        url: 'Localhost:4200',
        isFavorite: true,
        whenWasItReaded: new Date('2024-02-15'),
        rating: 8,
      },
      {
        chapter: '142',
        title: "The Heavenly Demon Can't Live a Normal Life",
        url: 'https://asuracomic.net/series/the-heavenly-demon-cant-live-a-normal-life-f04530a5/chapter/139',
        isFavorite: false,
        whenWasItReaded: new Date('2024-03-21'),
        rating: 9,
      },
      {
        chapter: '38',
        title: 'Solo Leveling: Ragnarok',
        url: 'https://asuracomic.net/series/solo-leveling-ragnarok-29d48e23/chapter/37',
        isFavorite: true,
        whenWasItReaded: new Date('2024-07-13'),
        rating: 7,
      },
      {
        chapter: '124',
        title: 'SSS-Class Suicide Hunter',
        url: 'https://asuracomic.net/series/sss-class-suicide-hunter-c35bcf93/chapter/124',
        isFavorite: false,
        whenWasItReaded: new Date('2024-01-29'),
        rating: 10,
      },
      {
        chapter: '50',
        title: 'The Reincarnated Assassin is a Genius Swordsman',
        url: 'https://asuracomic.net/series/the-reincarnated-assassin-is-a-genius-swordsman-983c6d17/chapter/50',
        isFavorite: true,
        whenWasItReaded: new Date('2024-06-18'),
        rating: 8,
      },
      {
        chapter: '68',
        title: 'Worthless Regression',
        url: 'https://asuracomic.net/series/worthless-regression-50201282/chapter/68',
        isFavorite: false,
        whenWasItReaded: new Date('2024-08-05'),
        rating: 6,
      },
      {
        chapter: '46',
        title: 'The Executioner',
        url: 'https://asuracomic.net/series/the-executioner-472e692a/chapter/46',
        isFavorite: true,
        whenWasItReaded: new Date('2024-11-22'),
        rating: 7,
      },
      {
        chapter: '141',
        title: 'Return of the SSS-Class Ranker',
        url: 'https://asuracomic.net/series/return-of-the-sss-class-ranker-d51a3031/chapter/141',
        isFavorite: false,
        whenWasItReaded: new Date('2024-05-09'),
        rating: 9,
      },
      {
        chapter: '136',
        title: 'Trash of the Count’s Family',
        url: 'https://asuracomic.net/series/trash-of-the-counts-family-38493e56/chapter/136',
        isFavorite: true,
        whenWasItReaded: new Date('2024-03-17'),
        rating: 8,
      },
      {
        chapter: '132',
        title: 'Pick Me Up, Infinite Gacha',
        url: 'https://asuracomic.net/series/pick-me-up-infinite-gacha-5803ee65/chapter/132',
        isFavorite: true,
        whenWasItReaded: new Date('2024-04-02'),
        rating: 10,
      },
      {
        chapter: '110',
        title: 'Return of the Disaster-Class Hero',
        url: 'https://asuracomic.net/series/return-of-the-disaster-class-hero-a31a2306/chapter/110',
        isFavorite: false,
        whenWasItReaded: new Date('2024-02-20'),
        rating: 7,
      },
      {
        chapter: '72',
        title: 'The Priest of Corruption',
        url: 'https://asuracomic.net/series/the-priest-of-corruption-7e4b6868/chapter/72',
        isFavorite: false,
        whenWasItReaded: new Date('2024-06-25'),
        rating: 6,
      },
      {
        chapter: '120',
        title: 'Duke Pendragon',
        url: 'https://asuracomic.net/series/duke-pendragon-353743ee/chapter/120',
        isFavorite: true,
        whenWasItReaded: new Date('2024-07-19'),
        rating: 8,
      },
      {
        chapter: '118',
        title: 'Dungeon Odyssey',
        url: 'https://asuracomic.net/series/dungeon-odyssey-b688584e/chapter/118',
        isFavorite: true,
        whenWasItReaded: new Date('2024-09-03'),
        rating: 10,
      },
      {
        chapter: '23',
        title: "A Dragonslayer's Peerless Regression",
        url: 'https://asuracomic.net/series/a-dragonslayers-peerless-regression-aaa07236/chapter/23',
        isFavorite: false,
        whenWasItReaded: new Date('2024-08-14'),
        rating: 5,
      },
      {
        chapter: '115',
        title: 'I Obtained a Mythic Item',
        url: 'https://asuracomic.net/series/i-obtained-a-mythic-item-09437f9f/chapter/115',
        isFavorite: true,
        whenWasItReaded: new Date('2024-10-10'),
        rating: 9,
      },
      {
        chapter: '117',
        title: 'Absolute Sword Sense',
        url: 'https://asuracomic.net/series/absolute-sword-sense-6617ba0b/chapter/117',
        isFavorite: false,
        whenWasItReaded: new Date('2024-11-04'),
        rating: 7,
      },
      {
        chapter: '16',
        title: 'The Heavenly Demon Wants a Quiet Life',
        url: 'https://asuracomic.net/series/the-heavenly-demon-wants-a-quiet-life-71be586c/chapter/16',
        isFavorite: true,
        whenWasItReaded: new Date('2024-03-12'),
        rating: 8,
      },
      {
        chapter: '96',
        title: 'My School Life Pretending To Be a Worthless Person',
        url: 'https://asuracomic.net/series/my-school-life-pretending-to-be-a-worthless-person-4fbaf58c/chapter/96',
        isFavorite: false,
        whenWasItReaded: new Date('2024-06-01'),
        rating: 6,
      },
      {
        chapter: '246',
        title: 'Omniscient Reader’s Viewpoint',
        url: 'https://asuracomic.net/series/omniscient-readers-viewpoint-7fc01755/chapter/246',
        isFavorite: true,
        whenWasItReaded: new Date('2024-12-01'),
        rating: 9,
      },
    ]);
  }
}
